name: Action git add commit push
description: "GitHub action: 'git add .', 'git commit', 'git push'"
author: Nicholas Valentinus
branding:
  icon: moon
  color: gray-dark

inputs:
  name:
    description: Git name
    default: foo-bar-baz
  email:
    description: Git email
    default: d509a20fde23a@cce9157b209ed23e9
  msg:
    description: commit message
    default: Committed by GitHub Actions.

runs:
  using: 'composite'
  steps:
    - run: |
        echo "::group::Committing"
        echo "INFO: version: v1.2.1"
        git config user.name "${{ inputs.name }}"
        git config user.email "${{ inputs.email }}"
        git add .
        git commit -m "$MSG"
        git push
        echo "::endgroup::"
      shell: bash
      env:
        MSG: ${{ inputs.msg }}  # Using env, in case the message has backtick (`) characters.