name: action git add commit push
description: "GitHub action: 'git add .', 'git commit', 'git push'"
author: Nicholas Valentinus
branding:
  icon: moon
  color: gray-dark

inputs:
  name:
    description: Git name
    required: false
    default: ${{ github.event }}
  email:
    description: Git email
    required: false
    default: 'foo'
  msg:
    description: commit message
    required: false
    default: "Commited — $(date +'%Y %b %e, %l:%M %p')"

runs:
  using: 'composite'
  steps:      
    - shell: bash
      run: |
        echo "${{ inputs.name }}"
        echo "${{ inputs.email }}"
        echo "${{ inputs.msg }}"
        # git config user.name "${{ inputs.name }}"
        # git config user.email "${{ inputs.email }}"
        # git add .
        # git commit -m "${{ inputs.msg }}"
        # git push